---
# PowerStore NFS Storage Class
# Supports ReadWriteMany (RWX) access mode for live migration
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: powerstore-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    description: "PowerStore NFS storage with RWX support for VM live migration"
parameters:
  # PowerStore array ID (update to match your array)
  arrayID: "PS03455f439da7"

  # NAS server name (configured in PowerStore driver secret)
  nasName: "nas1"

  # Filesystem type
  csi.storage.k8s.io/fstype: "nfs"

provisioner: csi-powerstore.dellemc.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

# NFS mount options
mountOptions:
  - nfsvers=4.1
  - hard
  - timeo=600
  - retrans=2
  - rsize=1048576
  - wsize=1048576
