---
# PowerStore Performance Test Configuration
# This configuration tests with larger scale to measure performance
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-checkup-config
  namespace: kubevirt-storage-checkup-test
data:
  # Longer timeout for performance testing
  spec.timeout: "30m"

  # Platform
  spec.param.platform: "vanilla-k8s"

  # Golden images namespace
  spec.param.goldenImagesNamespace: "kubevirt-os-images"

  # Storage class
  spec.param.storageClass: "powerstore-iscsi"

  # Longer VM timeout for larger scale
  spec.param.vmiTimeout: "5m"

  # Boot 20 VMs concurrently to test performance
  spec.param.numOfVMs: "20"

  # Always cleanup after performance test
  spec.param.skipTeardown: "never"
